default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>

development:
  <<: *default
  channel_prefix: cordless_development

test:
  adapter: test

performance:
  <<: *default
  channel_prefix: cordless_performance

production:
  <<: *default
  channel_prefix: cordless_production
